config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'products/search' => 'products#search', as: 'search_products'
  post 'emaillist/subscribe' => 'emaillist#subscribe'
  resources :categories
  resources :labels
  resources :products do
    resources :product_items
  end
   
   

  resources :carts 
   
  
  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contacts, only: [:new, :create]

   root 'pages#index'

   
  get 'about' => 'pages#about'

  get 'location' => 'pages#location'

  get  'help' => 'pages#help'

  get  'terms' => 'pages#terms'

   get  'privacy' => 'pages#privacy'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

	has_many :product_items, dependent: :destroy

	def add_product(product_id)
		current_item = product_items.find_by(product_id: product_id)
		if current_item
			current_item.quantity += 1
			
		else
			current_item = product_items.build(product_id: product_id)
		end
		current_item


	end

	def remove_product(product_id)
		current_item = product_items.find_by(product_id: product_id)
		if current_item
			current_item.quantity -= 1
			
		else
			current_item = product_items.build(product_id: product_id)
		end
		current_item


	end

	def total_price_usd
		product_items.to_a.sum{|item| item.total_price_usd}
	end

	def total_price_isl
		product_items.to_a.sum{|item| item.total_price_isl}
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

	before_action :set_cart, only: [:show, :destroy]
	#rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

	def new
		@cart = Cart.new
	end

	def show
		@meta_title = "Hlín Reykdal - Cart"

		 @images  = ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"]
     @random_no = rand(5)
     @random_image = @images[@random_no]

	end


	#def destroy
	#	@cart.destroy if @cart.id == session[:cart_id]
	#	session[:cart_id] = nil
	#	product = Product.find params[:product_id]
     #   product.update_columns(stock_quantity: product.stock_quantity + 1)
	#	redirect_to root_url, notice: 'Your Cart is Empty'
	#end

	def destroy
      if @cart.id == session[:cart_id]
        @cart.product_items.each do |product_item|
          product_item.product.update_columns(stock_quantity: product_item.product.stock_quantity + 1)
       end
       @cart.destroy
       redirect_to root_url, notice: 'Your Cart is Empty'
      end
    end

	
	private

	def set_cart
		@cart = Cart.find(params[:id])
	end

	def cart_params
		params[:cart]
	end

	def invalid_cart
		logger_error = 'You are trying to access invalid cart'
		redirect_to root_url, notice: 'Invalid Cart'
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% @cart.product_items.each do |item| %>

	<table class="table">
		<tr>
			<th>Quantity</th>
			<th>Name</th>
			<th>Price &euro;</th>
			<th>Price ISK</th>
			<th>Image</th>

		</tr>
		<tr>
			<td><%= item.quantity %>&times; </td>
			<td><%= item.product.title %></td>
			<td><%= number_to_currency(item.total_price_usd, :unit => '€ ', :precision => 0)%></td>
			<td><%= number_to_currency(item.total_price_isl.to_i, :unit => "ISK ", :precision => 0) %></td>
			<td><%= image_tag item.product.images.first.image.url(:thumb) %></td>
			
		</tr>

		</table>
	
<%end %>


<%#= button_to product_product_item_path(params[:product_id]), method: :delete, class: 'buttons-style' do %>
          <!--<i class="fa fa-shopping-cart"></i>Remove from to Cart -->
<%# end %>

app/views/carts/show.html.erb
<header id="necklace_header" class="img-responsive">


  <img src="/assets/rand_headers/<%= @random_image%>", style='height:auto;width:100%;' >
	
	
</header>

<div class="row product_top">


<div class="container cart-container">
<h3> Your Cart </h3>
<h4> Cart Details </h4>

<br>

<%= render 'carts/cart' %>

<br>
<hr>
<br>
<h5>Total: <%= number_to_currency(@cart.total_price_usd, :unit => "€ ", :precision => 0)%> </h5>

<h5>Total: <%= number_to_currency(@cart.total_price_isl.to_i, :unit => "ISK ", :precision => 0) %> </h5>
<br>
<%= link_to 'Back', root_path, class: 'pull-right cart-links' %>
<br>
<%= link_to 'Empty Your Cart', @cart, method: :delete, data: {confirm: 'Are You Sure?'}, class: 'pull-right cart-links' %>
<hr>
<br>
	<%= button_to 'Checkout', new_order_path, method: :get, class: 'pull-right buttons' %>
<br>


</div>
</div>