config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'products/search' => 'products#search', as: 'search_products'
  post 'emaillist/subscribe' => 'emaillist#subscribe'
  resources :categories
  resources :labels
  resources :products do
    resources :product_items
  end
   
   

  resources :carts 
   
  
  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contacts, only: [:new, :create]

   root 'pages#index'

   
  get 'about' => 'pages#about'

  get 'location' => 'pages#location'

  get  'help' => 'pages#help'

  get  'terms' => 'pages#terms'

   get  'privacy' => 'pages#privacy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :find_categories
  before_action :find_labels
  before_action :set_cart

 

    def find_categories
    	cururl = request.original_url
    	cururl.to_s
    if cururl.include? "admin"
      ##Dont run navi code!
    else
  	@categories = Category.all
  end
  end

  def find_labels
    cururl = request.original_url
      cururl.to_s
    if cururl.include? "admin"
      ##Dont run navi code!
    else

    @labels = Label.all
  end
end
 
 def set_cart
    @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_contact_errors.html.erb
<% unless @contact.errors.empty? %>
	<script type="text/javascript">
	<% @contact.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>	

	</script>

<% end %>

app/views/application/_footer.html.erb
<footer id="footer" class="footer">
<div class="container-fluid">
      <div class="row">
        

        <div class="col-xs-12 col-md-3 text-center" id="footer_nav">
        
      
         <ul>
         <li>Fiskislóð 75</li>
          <li>101, Reykjavík</li>
          <li><a href="tel:+354-5711407">+354-5711407</a>
          <h5>Open</h5>
          <li> Mon - Fri: 11-18 </li>
          <li> Sat: 11-16 </li>
          <li> Sun: Closed </li>
          </ul>

        </div>
       
         <div class="col-xs-12 col-md-3 text-center pull-right" id="footer_nav">
            <ul>  
                        <h5>Categories</h5>
                         <% @categories.each do |category| %>
                            <li><%= link_to category.name, category %></li>
                        <% end %>  
            </ul>
           
            </div>  
            <div class="col-xs-12 col-md-3 text-center pull-right" id="footer_nav">
                <ul>
                      <h5>Labels</h5>
                
                       <% @labels.each do |label| %>
                            <li><%= link_to label.name, label %></li>
                        <% end %>   
                              
                </ul>   
                    
            </div>          
            
                
              <div class="col-xs-12 col-md-3 text-center pull-right" id="footer_nav">

              <h5>Info</h5>
                    <ul>                   
                         <li><%= link_to "About", about_path %></li>
                        
                        <li><%#= link_to "Stockists", stockists_path %></li> 
                    
                        
                        <li><%= link_to "Location", location_path %></li>
                        
                        <li><%= link_to "Help", help_path %></li> 
                        
                    </ul>
             </div>

      </div>
             <div class="row footer-bottom text-center">
          <ul>
            <li><a href="https://www.instagram.com/hlinreykdalstudio/"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>

            <li> <a href="https://www.facebook.com/Hl%C3%ADn-Reykdal-208910763506/?fref=ts"> <i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>

            <li><i class="fa fa-envelope" aria-hidden="true"></i></li>
          </ul>
        </div>
    </div>

       
      
    </footer>

app/views/application/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
	<% flash.each do |f| %>
		<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>'] ('<%= f[1] %>')
		 <% end %>

	</script>

	<% end %>
	

app/views/application/_msg.html.erb
<% unless @order.errors.empty? %>
	<script type="text/javascript">
	<% @order.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>	

	</script>

<% end %>

app/views/application/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">		
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" 
                    data-toggle="collapse" 
                    data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <%= link_to image_tag("logo.svg", style:'height:auto;width:168px;'), root_path, class: 'navbar-brand' %>
          
        </div>
        <!-- Navbar Links -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                        Store
                    </a>


                    <ul class="dropdown-menu" role="menu">
                    

                        <% @categories.each do |category| %>
                            <li><%= link_to category.name, category %></li>
                        <% end %>    
                
                    </ul>
                </li>       
                   

                  <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                        Labels
                    </a>


                    <ul class="dropdown-menu" role="menu">
                    
                       
                       <% @labels.each do |label| %>
                            <li><%= link_to label.name, label %></li>
                        <% end %>    
                           
                       
                 
                        
                    </ul>
                </li>       


      
                <li class="dropdown full-width">
                    <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">
                        Info
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "About", about_path %></li>
                        <li><%= link_to "Contact", new_contact_path %></li>
                        <li><%#= link_to "Stockists", stockists_path %></li> 
                    
                        <li class="divider"></li>
                        <li><%= link_to "Location", location_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Help", help_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Terms & Conditions", terms_path %></li>
                         <li class="divider"></li>
                        <li><%= link_to "Privacy", privacy_path %></li>
                    </ul>
                </li>          
           
                
                <li class="searchbar">

                    <%= form_tag search_products_path, method: 'get', class: 'navbar-form' do %>
                    <%= text_field_tag :query, params[:query], placeholder: "Enter search term", class: "form-control transparent-input",
        :style => "padding-left:29px" %>
                    <%= button_tag(type: 'submit', class: "search-button transparent-input") do %> <span class="glyphicon glyphicon-search "></span>   
  
                    <% end %>
                <% end %>

                </li>


                <li class="dropdown full-width navbar-right cart-wrapper">

                <%# if @cart.total_price_usd > 0 %>
                    <%#= link_to @cart do %> 
                        <!--<i class="fa fa-shopping-cart"> &euro; </i>-->
                    <%#=  @cart.total_price_usd %>
                    <%# end %>

                    <%# else %>
                       <!-- <a href="#" class="menu-cart"><i class="fa fa-shopping-cart"></i> &euro; 0.00</a> -->
                    <%# end %>    

                    <% if @cart.product_items.count > 0 %>
                    <%= link_to @cart do %> 
                        <i class="fa fa-shopping-cart"></i>
                    <%= @cart.product_items.count %>
                    <% end %>

                    <% else %>

                    <a href="#" class="menu-cart"><i class="fa fa-shopping-cart"></i> 0 </a>
                    <% end %>    

                </li>


                                
                    
                </li>     
            </ul>
        </div>
       </div> 
    </div>

    
<script>
  /**
 * Listen to scroll to change header opacity class
 */
function checkScroll(){
    var startY = $('.navbar').height() * 2; //The point where the navbar changes in px

    if($(window).scrollTop() > startY){
        $('.navbar').addClass("scrolled");
    }else{
        $('.navbar').removeClass("scrolled");
    }
}

if($('.navbar').length > 0){
    $(window).on("scroll load resize", function(){
        checkScroll();
    });
}
</script>
<script>
    $('.dropdown').hover(
        function() {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn();
        }, 
        function() {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut();
        }
    );

    $('.dropdown-menu').hover(
        function() {
            $(this).stop(true, true);
        },
        function() {
            $(this).stop(true, true).delay(200).fadeOut();
        }
    );
</script>

app/views/application/_notifications.html.erb
<div id="site-notification">
	<div>
		<p class="postlist-text"data-toggle="modal" data-target="#myModal">Please subscribe to our postlist</p> 
		<button class="close"></button>
	</div>

</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Please subscribe to our post list</h4>
      </div>
      <div class="modal-body">
        <%= render 'emaillist/email' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){
    $("#site-notification").click(function(){
        $("#site-notification").hide();
    });
        
});
</script>