config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'products/search' => 'products#search', as: 'search_products'
  post 'emaillist/subscribe' => 'emaillist#subscribe'
  resources :categories
  resources :labels
  resources :products do
    resources :product_items
  end
   
   

  resources :carts 
   
  
  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :contacts, only: [:new, :create]

   root 'pages#index'

   
  get 'about' => 'pages#about'

  get 'location' => 'pages#location'

  get  'help' => 'pages#help'

  get  'terms' => 'pages#terms'

   get  'privacy' => 'pages#privacy'

end

app/models/product.rb
class Product < ActiveRecord::Base
	acts_as_list :scope => [:category, :label]
	belongs_to :category
	belongs_to :label

	has_many :images
	accepts_nested_attributes_for :images
	has_many :product_items, :dependent => :destroy



	 extend FriendlyId
     friendly_id :title, use: [:slugged, :finders]

	#before_destroy :ensure_not_product_item
	
	

		validates :title, :description, presence: true
		validates :price_usd, :price_isl, numericality: {greater_than_or_equal_to: 0.01}
		validates :title, uniqueness: true
	


  	 #def ensure_not_product_item
  	 #	if product_item.empty?
  	 #		return true
  	 #	else
  	 #		errors.add(:base, 'You have Product Items')
  	 #		return false
  	 #	end

  	 #end

  	 def self.search(query)
		
     where("title LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%") 
    end
end

app/controllers/products_controller.rb
 class ProductsController < ApplicationController
 	before_action :set_product, only: [:show, :edit, :update, :destroy]


 	  def show

      offset = rand(100)
      @meta_title = "Hlín Reykdal #{@product.title}"
      @meta_description = @product.description
      @products_rand = Product.where(category_id: @product.category_id).order("RANDOM()").limit(6)
     end

  def search
    
    @product = Product.search(params[:query]).order("created_at DESC")
    @categories = Category.joins(:products).where(:products => {:id => @product.map{|x| x.id }}).distinct


  end

 	private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price_usd, :price_isl, :image, :category_id, :stock_quantity, :label_id, :query, :slug, images_attributes: [:image , :id , :_destroy])
    end

  
 end

app/views/products/search.html.erb
<div class="container">
<div class="row product_top">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Designer</th>
      <th>Price</th>
      <th>Stock</th>
      <th>Image</th>
      
    </tr>
  </thead>

<tbody>
  <% @product.each do |product| %>
    
      <tr>
        <td><%= link_to product.title, product %></td>
        <td><%= product.description %></td>
        <td><%= product.label.name %></td>

        <td><%#= number_to_currency product.price %></td>
        <td><%= product.stock_quantity %></td>

        <td><%= image_tag product.image.url(:thumb)%></td>
      
 
  <% end %>
  </tr>
</tbody>
</table>
</div>
</div>

app/views/products/show.html.erb
    
    <div class="container">
	 
      <div class="row product_top text-center">

       <div class="col-xs-12 col-sm-6 center-block">
    
       
       <div class="product_description">

        <h3 class="title"><%= @product.title %></h3>
        <p class="label-product"><%= @product.label.name %></p>

        <p class="description">Description</p>
               
        <p class="product-description"><%= @product.description.html_safe %></p>
        
       

            <% if @product.stock_quantity <= 0 %>
     

       <p> Out of stock </p> 

            <% end %>
     </div>
      	<div class="col-xs-12">
       	 <p class="product-price"> Price:</p> <%= number_to_currency(@product.price_usd, :unit => "€ " , :precision => 0) %> | <%= number_to_currency(@product.price_isl.to_i, :unit => "IKR " , :precision => 0) %>
    	</div>

       <%# if @product.stock_quantity >= 1 %>
    	<div class="row text-center add-cart-wrapper">	
        	
          <% if @product.stock_quantity >= 1 %>

          <%= link_to 'Add to Cart', product_product_items_path(@product), :method => :post, class: 'add-to-cart'%>

         <% end %>

       </div>
  
   
    </div>

      

 
  <div class="col-xs-12 col-sm-6 center-block" >



    <div id='carousel-custom' class='carousel slide' data-ride='carousel'>
        <div class='carousel-outer'>
            <!-- me art lab slider -->
            <div class='carousel-inner '>
                <div class='item active'>
                    <%= image_tag @product.images.first.image.url(:medium), class: "img-responsive", id: "" %>
                </div>
                
                    <% @product.images.drop(1).each do |image_product| %>
                    <div class='item'>
                        <%= image_tag image_product.image.url(:medium), class: "img-responsive", id: "" %>
                  
                </div>
                  <% end %>

                <script>
                  $("#zoom_05").elevateZoom({ zoomType    : "inner", cursor: "crosshair" });
                </script>
            </div>
            <!-- sag sol -->
            <a class='left carousel-control' href='#carousel-custom' data-slide='prev'>
                <span class='glyphicon glyphicon-chevron-left'></span>
            </a>
            <a class='right carousel-control' href='#carousel-custom' data-slide='next'>
                <span class='glyphicon glyphicon-chevron-right'></span>
            </a>
        </div>
                    <!-- thumb -->
        <ol class='carousel-indicators mCustomScrollbar meartlab'>
            <li data-target='#carousel-custom' data-slide-to='0' class='active'>
                <%= image_tag @product.images.first.image.url(:medium), class: "img-responsive", id: "zoom_05" %>
            </li>
            <% @product.images[1..-1].each_with_index do |image_product, index| %>
                <li data-target='#carousel-custom' data-slide-to=<%= index + 1%> >
                    <%= image_tag image_product.image.url(:medium), class: "img-responsive", id: "" %>
                </li>
            <% end %>
            </li>
        </ol>
       </div>
      </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $(".mCustomScrollbar").mCustomScrollbar({axis:"x"});
        });
    </script>

</div>





  <div class="row container product-teaser">

  <h4 class="text-center teaser-text"> similar products to <%= @product.title %> : </h4>
   <% @products_rand.each do |product| %>
      <div class="col-sm-2 col-xs-3 center-block product-thumbs-product-view" >

  <%= link_to product_path (product) do %>
    <% if product.images.first %>
                <%= image_tag product.images.first.image.url(:medium), :size => "100%x100%", class: "img-responsive center-block" %>
        <% end %>        
            <% end %>



          <h5 class="text-center"><%= link_to product.title, product, class: "text-center" %></h5>

      </div>
    <% end %>

  </div>

</div>  
</div>
</div>
</div>
</div>





<%#= button_to product_product_items_path( @product), class: 'buttons-style' do %>
          <!--<i class="fa fa-shopping-cart"></i>Add to Cart-->
         <%# end %>